insert into DEPARTMENT values (101, 'Office', 'Admins')
insert into DEPARTMENT values (201, 'Construction', 'Construction Department')
insert into DEPARTMENT values (202, 'Construction', 'Storage')
insert into DEPARTMENT values (102, 'Office', 'Accounting')
insert into DEPARTMENT values (103, 'Office', 'Engineering')
